sudo: required

dist: xenial

services: docker

language: bash

env:
  global:
    - ALLURE_RELEASE=2.17.X
    - TARGET=frankescobar/allure-docker-service
    - QEMU_VERSION=v4.0.0
  matrix:
    - DOCKER_FILE=Dockerfile.bionic ARCH=amd64   JDK=adoptopenjdk:11-jre-openj9-bionic  QEMU_ARCH=x86_64
    - DOCKER_FILE=Dockerfile.bionic ARCH=arm32v7 JDK=adoptopenjdk:11-jdk-hotspot-bionic QEMU_ARCH=arm
    - DOCKER_FILE=Dockerfile.bionic ARCH=arm64v8 JDK=adoptopenjdk:11-jre-hotspot-bionic QEMU_ARCH=aarch64

before_install:
  - ./docker/docker.sh prepare

install: true

before_script:
  # Set BUILD_VERSION
  - if [ ! -z "${TRAVIS_TAG}" ]; then export BUILD_VERSION=${TRAVIS_TAG:1}; else export BUILD_VERSION=beta; fi

script:
  # Build Docker image
  - ./docker/docker.sh build

  # Test Docker image
  - ./docker/docker.sh test

  # Push Docker image, ony if TRAVIS_TAG is set
  - >
    if [ ! -z "${TRAVIS_TAG}" ]; then
      # Tag Docker image
      ./docker/docker.sh tag

      # Docker Login
      echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      # Push Docker image
      ./docker/docker.sh push

      # Docker Logout
      docker logout
    fi

jobs:
  include:
    - stage: manifest
      # Only create and push manifest list to Docker Hub, when tag starts with a `v`, eg. v2.12.1
      if: tag =~ ^v
      script:
        # Create and push Docker manifest lists
        # Docker Login
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

        # Create and Push Docker Manifest Lists to Docker Hub
        - echo "Create manifest list for all docker images."
        - ./docker/docker.sh manifest-list

        # Docker Logout
        - docker logout

# notify me when things fail
notifications:
  email: true
